apiVersion: dana.io.namespacelabel.com/v1alpha1
kind: NamespaceLabel
metadata:
  labels:
    app.kubernetes.io/name: nsl-operator-tal
    app.kubernetes.io/managed-by: kustomize
  name: namespacelabel-sample
spec:
  # TODO(user): Add fields here
